### PR TITLE
Ensure UserManager can only be instantiated once

### PR DESCRIPTION
**Pull request by TheNeikos**
## Proposed changes

This change makes the `UserManager` only creatable once per process.

(From https://github.com/thin-edge/thin-edge.io/pull/841#discussion_r802467124)

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

This change can cause problems in tests, as they are all run in a single excecutable. A possible fix for this can be that the check requirement is disabled when in `test` environment.

### CODE REVIEW

**Comment by TheNeikos** [comment]
As expected the tests requiring a UserManager in the same process fail.

- It will not be enough to restore the `AtomicBool` to `true` on `Drop`. As tests are run in parallel they will certainly fail. 
- The documentation is clear that it should only ever be created once.

**Comment by TheNeikos** [comment]
@didier-wenzek What do you think should be done about the failing tests?

**Comment by didier-wenzek** [comment]
> @didier-wenzek What do you think should be done about the failing tests?

@PradeepKiruvale is working on the [sporadic failure of get_jwt_token_full_run](https://github.com/thin-edge/thin-edge.io/issues/833). He found the breaking point (the test client fails to connect to the test server when this one has just been launched). He should come with a fix or a workaround tomorrow.

Meantime, let's just rerun the checks.

**Comment by matthiasbeyer** [comment]
@TheNeikos I am 100% sure is not talking about the jwt thing, but about [the test failures](https://github.com/thin-edge/thin-edge.io/runs/5126194171?check_suite_focus=true#step:7:397) that he expected

> This change can cause problems in tests, as they are all run in a single excecutable. A possible fix for this can be that the check requirement is disabled when in test environment.

and

> As expected the tests requiring a UserManager in the same process fail.

(see above).

**Comment by didier-wenzek** [comment]
> I am 100% sure that @TheNeikos is not talking about the jwt thing, but about [the test failures](https://github.com/thin-edge/thin-edge.io/runs/5126194171?check_suite_focus=true#step:7:397) that he expected
> 
> > This change can cause problems in tests, as they are all run in a single excecutable. A possible fix for this can be that the check requirement is disabled when in test environment.
> 
> and
> 
> > As expected the tests requiring a UserManager in the same process fail.
> 
> (see above).

Indeed, I missed that!

So, the response is, yes, the simpler is to let `UserManager::new()` builds new instances under `#[cfg(test)]`.

With a command like `sudo tedge connect c8y` is running, one must have at most one `UserManager` as this manager control the effective user id of the process. Having two different threads run with they `UserManager` would lead to undefined behaviors, each thread being enable to ensure that the other is not concurrently changing the effective user.

Hence, as long as the tests are launched using a regular user and not under root, having one or several `UserManager` has no side effects. The tests cannot and doesn't need to be granted extra privileges.

**Comment by matthiasbeyer** [comment]
> Hence, as long as the tests are launched using a regular user and not under root,

Maybe I am missing something, but why would anyone ever run tests as root? I assume we talk about `cargo test` tests?

**Comment by didier-wenzek** [comment]
>> Hence, as long as the tests are launched using a regular user and not under root,

> Maybe I am missing something, but why would anyone ever run tests as root? I assume we talk about cargo test tests?

I should have written: "*since* the tests are launched using a regular user and not under root, ..."

**Comment by didier-wenzek** [comment]
This PR can be closed. Mainly because it would be better to [deprecate the `UserManager`](https://github.com/thin-edge/thin-edge.io/issues/1207).

**Pull request closed without merging**
