### PR TITLE
tedge_util style fixes

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Proposed changes

Hi!

While browsing the code of the `tedge_util`I found some things that can be improved style-wise.

Please find my patches, where I expressed what I did in great detail in the commit messages, so that others can understand why a specific change was done.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by didier-wenzek — COMMENTED** [review]
Thanks. I will approve once fixed the test build issue.

**Comment by matthiasbeyer** [comment]
Whoopsi, that slipped through. Sorry about that.

**Comment by rina23q** [comment]
Thank you!!!

**Review by PradeepKiruvale — COMMENTED** [review]
LGTM

**Review by didier-wenzek — APPROVED** [review]
Approved

**Review by rina23q — APPROVED** [review]

**Pull request merged**
