### PR TITLE
[955] over write the apt plugin exit code

### PR DESCRIPTION
**Pull request by PradeepKiruvale**
## Proposed changes
This PR addresses the apt plugin exit code when the plugin fails due to no args or wrong args.
`Clap` returns `exit code 2` on failure when there are wrong args, but this has to be `1` as per the plugin specification.
So, we overwrite the exit code to `1`.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by didier-wenzek — COMMENTED** [review]
I'm  not really happy with this change forced by a crate we depend on.

* There are some explanations for this choice here https://github.com/clap-rs/clap/pull/2604. But it's unfortunate that we have no way to configure it.
* For this PR to complete, one also need to update the specifications for the sm-plugin return types.

**Comment by abelikt** [comment]
I do not have strong feelings about the error codes, but I believe we should check with our architect and change the spec in the same PR when we decide to change them. There might be also side effects with other plugins.

Keep in mind, that what I reported as observation in https://github.com/thin-edge/thin-edge.io/issues/955 is only the call without arguments (in the test tedge_agent_user_sudo_access). There is still a bit room for interpretation.
The calls with arguments, that Pradeep fixed in this PR, could still be interpreted as "The command failed ..." (exit code 2) without a spec change.

Here is a proposal for a minimal spec change to make clap, our spec and this PR for the tests compatible:
```
1 or 2(*): usage. The command arguments cannot be interpreted, and the command has not been launched.
2: failure. The command failed and there is no point to retry.

(*) Added to be compatible with the clap argument parser.
```

**Comment by didier-wenzek** [comment]
> Isn't it an option to stop using `clap` for our plugins? Plugins are not expected to be called by humans, so I think using clap is not necessary.
> 
> I am not happy to change our software management API specification because of what clap does.

That's indeed an option to explore.

**Review by abelikt — APPROVED** [review]
Looks good to me.
Also I missed the try_parse trick while reading the docs :)

**Review by rina23q — APPROVED** [review]
:+1:

**Review by didier-wenzek — CHANGES_REQUESTED** [review]
The fix is correct but the commit history is not.

* There is two commits, the second one reverting the first one and adding the proper fix.
* The title of the PR no more reflects its content.
* => please squash the commits or better close this PR and create a new one.

**Pull request merged**
