### PR TITLE
removing apt integration tests

### PR DESCRIPTION
**Pull request by initard**
## Proposed changes

- removed two tests that were hidden behind 2 feature flags:
  `integration-test` and `requires-sudo`. These tests were never running
  in the pipeline but after #1303 when the CI tool chain changed, they
  were re-enabled.
- these tests will be moved to system tests in the future.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Paste Link to the issue
#1304 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)

### CODE REVIEW

**Review by rina23q — APPROVED** [review]
Can you also remove line 8 & 9 from `ci_pipeline.yml`? It's no longer applicable.

```
# TODO: Safely move cargo test on amd64 to bash script
# TODO: Reduce complexity by moving functionality to bash scripts
```

**Review by rina23q — CHANGES_REQUESTED** [review]
Can you also change the argument of `cargo_build_tests_arm7_32bit`?

```yml
  cargo_build_tests_arm7_32bit:
    name: cargo build tests for armv7 32bit
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]
    steps:
    ........
      - name: Build tests cross release for target
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          use-cross: true
          command: test
          args: --release --no-run --target=armv7-unknown-linux-gnueabihf --all-features
```

**Review by matthiasbeyer — APPROVED** [review]
I am always pro removing unnecessary stuff, so :tada:

**Review by rina23q — APPROVED** [review]
perfect!

**Pull request merged**
