### PR TITLE
chore: bump MSRV in the workflow to 1.78

### PR DESCRIPTION
**Pull request by Ruadhri17**
## Proposed changes
This PR bumps MSRV in the workflow.  Version 1.78 introduced [diagnostic_attribute](https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html#diagnostic-attributes) that will be used in #2943.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by reubenmiller** [comment]
@Ruadhri17 I pushed a commit to fix some of the build matrix setup which was required since we can now use the default MSRV for all targets.

Though since we're using the merge queue the workflow won't use the new value in the `build-workflow.yaml` file, so it might make sense to do the `build-workflow.yaml` changes in one commit, then change the MSRV in a follow up PR

**Comment by Bravo555** [comment]
Can we bump to 1.79 instead? [It has improvements for extending lifetimes](https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html#extending-automatic-temporary-lifetime-extension), and I could really use that in my PR, without which I have to either do additional string clones or writing more complicated code using `Cow`.

**Comment by reubenmiller** [comment]
> meta-rust

Good catch about the `meta-rust` dependency. Good thing that 1.78 is supported by it.

**Review by didier-wenzek — APPROVED** [review]
Approved

**Pull request merged**
