### PR TITLE
packaging: align version schema used in packaging

### PR DESCRIPTION
**Pull request by reubenmiller**
## Proposed changes

Update version scheme used in packages to align with best practices.

**General**

* Use 7 letters to represent the commit hash to align with GitHub's default used in the UI
* Refactor version scripts to a single version.sh script which is sourced in the relevant scripts

**apk**

* Use version schema `x.x.x_rcN+gabcdef0-r0` to align with [Alpine Linux format](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#pkgver)

**tarball**

* Use version schema `x.x.x-rcN+gabcdef0` so that cloudsmith sorts packages built on the main branch correctly

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by didier-wenzek — COMMENTED** [review]
This works as explained.

However I have been surprised to see that once the user that a version, than `version.sh` stick on this version previously set.

```
$ . ci/build_scripts/version.sh 
$ echo $APK_VERSION '|' $DEB_VERSION '|' $RPM_VERSION '|'  $GIT_SEMVER
0.12.1_rc146+gbdc2ede | 0.12.1~146+gbdc2ede | 0.12.1~146+gbdc2ede | 0.12.1~146+gbdc2ede
$  . ci/build_scripts/version.sh --version 1.0                         
Using version set by user: 1.0
$ echo $APK_VERSION '|' $DEB_VERSION '|' $RPM_VERSION '|'  $GIT_SEMVER
1.0 | 1.0 | 1.0 | 1.0
$ . ci/build_scripts/version.sh                                       
Using version set by user: 1.0
$ echo $APK_VERSION '|' $DEB_VERSION '|' $RPM_VERSION '|'  $GIT_SEMVER
1.0 | 1.0 | 1.0 | 1.0
```

This is also surprising:

```
$ . ./ci/build_scripts/version.sh
Using version set by user: 0.12.1~146+gbdc2ede
```

At least it would be good to tell how to reset the version
 
```
$ unset GIT_SEMVER
$ ./ci/build_scripts/version.sh 
0.12.1~146+gbdc2ede
```

**Review by didier-wenzek — APPROVED** [review]
Approved.

**Comment by reubenmiller** [comment]
> This works as explained.
> 
> 
> 
> However I have been surprised to see that once the user that a version, than `version.sh` stick on this version previously set.
> 
> 
> 
> ```
> 
> $ . ci/build_scripts/version.sh 
> 
> $ echo $APK_VERSION '|' $DEB_VERSION '|' $RPM_VERSION '|'  $GIT_SEMVER
> 
> 0.12.1_rc146+gbdc2ede | 0.12.1~146+gbdc2ede | 0.12.1~146+gbdc2ede | 0.12.1~146+gbdc2ede
> 
> $  . ci/build_scripts/version.sh --version 1.0                         
> 
> Using version set by user: 1.0
> 
> $ echo $APK_VERSION '|' $DEB_VERSION '|' $RPM_VERSION '|'  $GIT_SEMVER
> 
> 1.0 | 1.0 | 1.0 | 1.0
> 
> $ . ci/build_scripts/version.sh                                       
> 
> Using version set by user: 1.0
> 
> $ echo $APK_VERSION '|' $DEB_VERSION '|' $RPM_VERSION '|'  $GIT_SEMVER
> 
> 1.0 | 1.0 | 1.0 | 1.0
> 
> ```
> 
> 
> 
> This is also surprising:
> 
> 
> 
> ```
> 
> $ . ./ci/build_scripts/version.sh
> 
> Using version set by user: 0.12.1~146+gbdc2ede
> 
> ```
> 
> 
> 
> At least it would be good to tell how to reset the version
> 
>  
> 
> ```
> 
> $ unset GIT_SEMVER
> 
> $ ./ci/build_scripts/version.sh 
> 
> 0.12.1~146+gbdc2ede
> 
> ```

Is the surprising bit the log message? as it gives the wrong impression that it was set by a user (when that is not always true)

**Comment by didier-wenzek** [comment]
> Is the surprising bit the log message? as it gives the wrong impression that it was set by a user (when that is not always true)

The surprising bit is that I was not expecting the version to be cached and furthermore in that case not set by me.

This is really minor.

**Comment by reubenmiller** [comment]
> > Is the surprising bit the log message? as it gives the wrong impression that it was set by a user (when that is not always true)
> 
> The surprising bit is that I was not expecting the version to be cached and furthermore in that case not set by me.
> 
> This is really minor.

Ah yes, correct. I guess I've never noticed it as I've sourced the version.sh script from other scripts in an isolated shell so it does not bleed the environment variables into my current shell's environment.

**Pull request merged**
