### PR TITLE
Closes #862 Report mosquitto cloud bridge health status via MQTT

### LINKED ISSUE #862: Monitor bridge status
Mosquitto provides a feature to monitor the status of a bridge connection. Enabling this feature will help to diagnose connection issues.

**AC:**

- The `tedge connect c8y` command includes the following lines in the `c8y-bridge.conf` bridge configuration file:

```
notifications true
notifications_local_only true
notification_topic tedge/status/bridge/c8y
```

Mosquitto will then publishes the status of the Cumulocity bridge to `tedge/status/bridge/c8y` using retained messages (`0` for down, `1` for up).
- The status in the topic also has to be updated in the case of disconnect and removed bridge config

**Notes**
* The current version set `notifications false` disabling the feature to avoid such notifications to be send to the cloud end-point. Setting both `notifications` and `notifications_local_only` prevents this side effect.
* The above configuration has to be adapted for each cloud (e.g `c8y` -> `az`).

### PR DESCRIPTION
**Pull request by albinsuresh**
## Proposed changes

Report mosquitto cloud bridge health status via MQTT. The reported status is just 0 or 1 and not any fancy JSON as reported by other tedge components as mosquitto doesn't allow customizations to that status message itself.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by PradeepKiruvale — COMMENTED** [review]
LGTM, who will subscribe to these `bridge health check` topics and how to use them?. Maybe some documentation is needed?

**Review by PradeepKiruvale — COMMENTED** [review]
1. Make this file extension as `.md`
2. Add this file link to Summary and README

**Comment by albinsuresh** [comment]
> 1. Make this file extension as `.md`
> 2. Add this file link to Summary and README

Done.

**Review by PradeepKiruvale — APPROVED** [review]
LGTM

**Pull request merged**
