### PR TITLE
Update cargo.lock check to 1.63.0

### PR DESCRIPTION
**Pull request by initard**
## Proposed changes

Updated CI task to use 1.63.0 to be in line with the other ones.  

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by didier-wenzek — APPROVED** [review]
Approved

**Review by rina23q — CHANGES_REQUESTED** [review]
Obviously, the change is not enough to update our MSRV to `1.63.0`. @didier-wenzek Did you decide to have `1.63.0` as our MSRV?

**Review by rina23q — APPROVED** [review]
Sorry, forget the previous comment. I didn't realise that we changed our MSRV. But we didn't update our building guide to `1.63.0`. This PR can be merged as it is, however, one should create another PR on the building guide ASAP.

https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/BUILDING.md

**Comment by rina23q** [comment]
I am totally confused now. Why workflows are using `1.63.0` toolchain although our `Cargo.toml` is specifying `1.58.1` as `rust-version = "1.58.1"`?

**Pull request merged**
