### PR TITLE
feat: report to the cloud workflow definition errors

### PR DESCRIPTION
**Pull request by didier-wenzek**
## Proposed changes

Replace any ill-defined workflow by a placeholder that fails all the commands for that operation and reports the workflow definition errors.

The aim is to fix the current situation where workflow definition errors are not reported to the clients, the corresponding operations being ignored and not reported to Cumulocity where they stay in the pending state for ever with no clue for the end-user. See https://github.com/thin-edge/thin-edge.io/issues/3074

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue

 - https://github.com/thin-edge/thin-edge.io/issues/3074

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by albinsuresh — COMMENTED** [review]
While testing this by overriding the `config_snapshot` workflow with an ill-formed definition, I encountered an issue where the operation stays in `executing state` in the cloud. The `config_snapshot` command is failing as expected and even getting mapped to a `502` message as follows:

```shell
te/device/main///cmd/config_snapshot/c8y-mapper-553305 {"status":"init","tedgeUrl":"http://127.0.0.1:8000/tedge/file-transfer/TST_lengthen_descent_refresh/config_snapshot/:etc:tedge:tedge.toml-c8y-mapper-553305","type":"/etc/tedge/tedge.toml"}
te/device/main///cmd/config_snapshot/c8y-mapper-553305 {"logPath":"/var/log/tedge/agent/workflow-config_snapshot-c8y-mapper-553305.log","reason":"Ignoring operation workflow definition from \"/etc/tedge/operations/config_snapshot.toml\": Parsing TOML content\n\nCaused by:\n    TOML parse error at line 1, column 1\n      |\n    1 | # An operation workflow with a typo\n      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    no variant of enum TomlOperationAction found in flattened data\n    ","status":"failed","tedgeUrl":"http://127.0.0.1:8000/tedge/file-transfer/TST_lengthen_descent_refresh/config_snapshot/:etc:tedge:tedge.toml-c8y-mapper-553305","type":"/etc/tedge/tedge.toml"}
c8y/s/us 502,c8y_UploadConfigFile,"Ignoring operation workflow definition from ""/etc/tedge/operations/config_snapshot.toml"": Parsing TOML content

Caused by:
    TOML parse error at line 1, column 1
      |
    1 | # An operation workflow with a typo
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    no variant of enum TomlOperationAction found in flattened data
    "
te/device/main///cmd/config_snapshot/c8y-mapper-553305 (null)
```

But, as you can see, the escaping of the failure message is messed up, which might be causing this issue.

**Review by gligorisaev — COMMENTED** [review]
Have checked and runned flake-finder, have no issues with it

**Comment by didier-wenzek** [comment]
> While testing this by overriding the `config_snapshot` workflow with an ill-formed definition, I encountered an issue where the operation stays in `executing state` in the cloud. The `config_snapshot` command is failing as expected and even getting mapped to a `502` message as follows:

This has been fixed by https://github.com/thin-edge/thin-edge.io/pull/3079/commits/d4c92c34210631999de8979de6754e2b3aa3a177

> But, as you can see, the escaping of the failure message is messed up, which might be causing this issue.

Actually, the issue was due to a missing "executing" step  (aka 501). Cumulocity was stuck waiting for it, ignoring all further messages.

This commit also improves the error messages forwarded to the cloud.

**Review by albinsuresh — APPROVED** [review]
LGTM.

This bug fix highlights another issue that we have with our error messages. I wish the toml parser returned more user-friendly error messages as a message like `no variant of enum TomlOperationAction found in flattened data` won't make much sense to the end user. We've got work to do on that front.

**Pull request merged**
