### PR TITLE
File permission API to change ownership of directory even if it already exists

### PR DESCRIPTION
**Pull request by albinsuresh**
## Proposed changes

When `tedge-agent` starts, the `/var/log/tedge/agent` directory is first created as `root` by the `operations_log` manager in `SmAgent::try_new` which is later changed to `tedge` in `SmAgent::init`. This fix makes such ownership changes of existing files possible.

The log directory could have been created as `tedge` at the beginning itself. Avoiding that for now, just to minimize the changes required for this bug fix. This will be fixed properly after the 0.7.6 release.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by didier-wenzek — APPROVED** [review]
Approved

**Review by initard — COMMENTED** [review]
LGTM but why `debug!` and not `error!`?

**Comment by initard** [comment]
Also your commit message seems to be too long and part of the title went to the body

**Comment by albinsuresh** [comment]
> LGTM but why `debug!` and not `error!`?

Because neither case is an error. If the directory was newly created, we just change the permission afterwards. Even in the other case where the directory already exits, previously we were ignoring it. But with this PR, we'll try to change the ownership. And that's also a valid case and not an error.

**Comment by initard** [comment]
> Because neither case is an error. If the directory was newly created, we just change the permission afterwards. Even in the other case where the directory already exits, previously we were ignoring it. But with this PR, we'll try to change the ownership. And that's also a valid case and not an error.

I see, then perhaps a `warn!` is more suitable? Anyways too late now :smile:

**Pull request merged**
