### PR TITLE
Fix: Flush the file buffer after writing to the file

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Proposed changes

This _may_(!!!) solve #1241.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue

#1241 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by didier-wenzek** [comment]
>   This may(!!!) solve https://github.com/thin-edge/thin-edge.io/issues/1241.

Indeed!

**Review by didier-wenzek — COMMENTED** [review]
* Do you have any idea to automate a test for this fix?
* This would also have to be done for the `atomically_write_file_sync` function.

**Comment by TheNeikos** [comment]
I don't know of any way that you could reliably check for it in this instance. However, flushing is always correct in this case, so whether it fixes the tests or not, it should get included imo.

**Review by didier-wenzek — APPROVED** [review]
Approved

**Pull request merged**
