### PR TITLE
fix: use MQTT as well as HTTP host to determine possible tenant url

### PR DESCRIPTION
**Pull request by jarhodes314**
## Proposed changes
Determine whether URLs are Cumulocity URLs based on both the HTTP and MQTT host, not just the HTTP host.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
- #2969 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by albinsuresh — COMMENTED** [review]
The logic is pretty straightforward for those having separate `c8y.http` and `c8y.mqtt` settings, and implemented as described in the ticket.

But, my understanding was that the end user sometimes may not even be aware of the internal URLs and they are only exposed to the external custom domains. So, they probably wouldn't even know that they need to configure both settings separately. This is the reason why querying the `https://your.custom.domain/tenant/loginOptions` endpoint was proposed as a better fix approach in #2804.

But, if it is guaranteed that custom domain users would configure their `tedge` like this with both the settings, then I'm happy to approve this PR.

**Comment by reubenmiller** [comment]
> The logic is pretty straightforward for those having separate `c8y.http` and `c8y.mqtt` settings, and implemented as described in the ticket.
> 
> But, my understanding was that the end user sometimes may not even be aware of the internal URLs and they are only exposed to the external custom domains. So, they probably wouldn't even know that they need to configure both settings separately. This is the reason why querying the `https://your.custom.domain/tenant/loginOptions` endpoint was proposed as a better fix approach in #2804.
> 
> But, if it is guaranteed that custom domain users would configure their `tedge` like this with both the settings, then I'm happy to approve this PR once the tests pass (a rebase required).

We can address the "easy of configuration" aspect to a separate PR. This PR is purely focusing on the case where the user knows that they have to use two separate URLs for the MQTT and HTTP traffic, however thin-edge.io may receive binaries either using the internal URL OR the custom domain name (as the user can manually use the custom domain when uploading binaries to their tenant).

**Review by didier-wenzek — APPROVED** [review]
Approved

**Comment by didier-wenzek** [comment]
There is a flaky test (unrelated to this PR) failing the merge queue :

```
test tests::test_cli_pub_basic::none_expects ... FAILED

failures:

---- tests::test_cli_pub_basic::none_expects stdout ----
thread 'tests::test_cli_pub_basic::none_expects' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/assert_cmd-2.0.13/src/output.rs:65:25:
command="/home/runner/work/thin-edge.io/thin-edge.io/target/llvm-cov-target/debug/tedge" "--config-dir" "/tmp/.tmp5EPpVm" "mqtt" "pub" "topic" "message"
code=1
stdout=""
stderr=
ERROR: the message has not been published
Error: failed to publish the message \"message\" on the topic \"topic\" with QoS \"AtMostOnce\".

Caused by:
    0: I/O: connection closed by peer
    1: connection closed by peer
```

**Pull request merged**
