### PR TITLE
Add "needs" on the Udeps job to run after Rust code changes

### PR DESCRIPTION
**Pull request by rina23q**
## Proposed changes
All jobs that require the filtering result must run after the filtering
job finishes. Refer to https://github.com/dorny/paths-filter#examples.

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
#1312 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by rina23q** [comment]
@matthiasbeyer See now "Udeps" is not skipped ;)

**Review by matthiasbeyer — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
Meh, but the build broke because the action needs nightly. Maybe we want to make the `udeps` job optional, so that it does not block the PR? :thinking: Unfortunate!

**Comment by rina23q** [comment]
> Meh, but the build broke because the action needs nightly. Maybe we want to make the `udeps` job optional, so that it does not block the PR? thinking Unfortunate!

The job is not "required", so even if it fails, we can merge. It doesn't look nice though :/

**Comment by rina23q** [comment]
@matthiasbeyer We have `RUSTFLAGS: -D warnings` [here](https://github.com/thin-edge/thin-edge.io/blob/main/.github/workflows/pull-request-checks.yml#L9), that makes the "udeps" failed even though it was warning.

```yml
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
```

What we maybe can do, is to add `RUSTFLAGS: -A warnings` only on the "udeps" job. Like below:
```yml
  udeps:
    name: Check for unused dependencies
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -A warnings
    if: ${{ needs.changes.outputs.rust == 'true' || needs.changes.outputs.workflows == 'true' }}
    steps:
    ...
```

How do you think? Then, the job won't fail by warnings (will fail by error)

**Comment by matthiasbeyer** [comment]
Well, I would rather do it the other way round and only set `-D warnings` on the jobs that should fail for warnings. Enabling it for everything and then selectively disabling it sounds like too much of a pitfall for future changes to the workflow definition to me... :thinking:

**Comment by rina23q** [comment]
Adding `-D warnings` to only specific jobs makes more sense. The jobs need it are
* cargo clippy
* cargo test (for compilation warnings)
* cargo build (for compilation warnings)
* cargo build for armv7 32bit (for compilation warnings)
* cargo build tests for armv7 32bit (for compilation warnings)

Do you agree? If yes, I can add a new commit here. So that we won't have red on Udeps after we merge this PR.

**Comment by matthiasbeyer** [comment]
Sounds reasonable!

**Comment by matthiasbeyer** [comment]
Whoop, I was able to update this PR with a change that moved the `RUSTFLAGS` setting, so you don't have to, @rina23q !

**Comment by rina23q** [comment]
Wow, thank you! Still the Udeps job is failing, but this time because we have unused dependencies. So, I would merge this PR and close the issue.

It's the output:
```
unused dependencies:
`mqtt_channel v0.7.3 (/home/runner/work/thin-edge.io/thin-edge.io/crates/common/mqtt_channel)`
└─── dependencies
     └─── "tedge_utils"
`tedge_utils v0.7.3 (/home/runner/work/thin-edge.io/thin-edge.io/crates/common/tedge_utils)`
└─── dependencies
     ├─── "anyhow"
     └─── "maplit"
```

**Pull request merged**
