### PR TITLE
Issue #1197 Document events API for child devices

### PR DESCRIPTION
**Pull request by albinsuresh**
## Proposed changes

Document events API for child devices

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [x] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by didier-wenzek** [comment]
This document says nothing about the [SmartREST 105](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#105) and [SmartREST 106](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#106) Cumulocity messages. Such a reference could be used to clarify the behavior of thin-edge when an event is send for a child device for the fist time.

**Comment by albinsuresh** [comment]
> This document says nothing about the [SmartREST 105](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#105) and [SmartREST 106](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#106) Cumulocity messages. Such a reference could be used to clarify the behavior of thin-edge when an event is send for a child device for the fist time.

Even though this was originally proposed in #1197, it was decided not to pre-populate the child id cache as it didn't offer any major benefits other than the trivial perf gain for the very first message. This decision was captured in this comment on that issue as well: https://github.com/thin-edge/thin-edge.io/issues/1197#issuecomment-1161542019

**Review by PradeepKiruvale — APPROVED** [review]
LGTM

**Comment by didier-wenzek** [comment]
> This document says nothing about the [SmartREST 105](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#105) and [SmartREST 106](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#106) Cumulocity messages. Such a reference could be used to clarify the behavior of thin-edge when an event is send for a child device for the fist time.

A consequence of ignoring what is declared on the cloud is that [deleted child devices are unintendedly recreated](https://github.com/thin-edge/thin-edge.io/issues/1340).

**Review by didier-wenzek — APPROVED** [review]
Approved

**Pull request merged**
