### PR TITLE
Simplify implementation of thin_edge_json::utils::excerpt

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Proposed changes

Simplify the implemementation of `thin_edge_json::utils::excerpt`.

## Types of changes

- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Maybe more tests should be added before this can be applied, so the equality of the code before and after the change is guaranteed.

Asking for review from @makr11st because the original author does not seem to belong to this project anymore?

### CODE REVIEW

**Review by didier-wenzek — APPROVED** [review]
Definitely nicer.

* This even highlight the unusual use of 1-indexing.
* I wonder if we can use a combination  of `intersperse` and `collect` rather than of `map(append)` and `flatten`. But these are details.

**Review by makr11st — APPROVED** [review]

**Comment by makr11st** [comment]
@matthiasbeyer Is there any problem with the merge that it is still open?

**Comment by matthiasbeyer** [comment]
Yes, the tests do not run successfully and I did not yet figure out what is the problem. I haven't looked at it too closely because I prioritized this rather low, tbh :laughing:

**Comment by didier-wenzek** [comment]
Superseded by https://github.com/thin-edge/thin-edge.io/pull/1604

**Pull request closed without merging**
