### PR TITLE
Use different branch of mneumann/rumqttc that has higher chance for

### PR DESCRIPTION
**Pull request by mneumann**
getting merged into upstream.

* The code is now based on branch [publish-correlated][1] which takes a
  slightly different approach.

* The old approach was passing a oneshot channel within the
  `Request::Publish`. A oneshot channel has the downside of being less
  introspectable.

* The new approach passes a `correlation_id` with the request and emits
  a PublishCorrelated event that contains the `pkid` and the
  `correlation_id`. This allows to associate a publish request with the
  used `pkid`.

* NOTE: The new branch does not contain major memory optimizations and
  sanity checks (less chances for "panics"), in favor of being easier to
  keep up-to-date with the master branch of upstream `rumqtt`
  repository.

* There is a separate PR for rumqttc about some of the performance work I did:

  https://github.com/bytebeamio/rumqtt/pull/239

[1]: https://github.com/mneumann/rumqtt/tree/publish-correlated

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactorings that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by makr11st — COMMENTED** [review]
In general we are still far behind the main of the crate and I don't think we benefit from the feature we added here as it is not even used in the code.
It makes the crate dependency almost impossible to maintain.

**Comment by mneumann** [comment]
@makr11st Fully agree. Though, I do think we use that code somewhere in `tedge mqtt pub --qos 1/2`, don't we?

**Comment by mneumann** [comment]
@didier-wenzek @makr11st please see https://github.com/thin-edge/thin-edge.io/pull/306 for an alternative.

**Comment by mneumann** [comment]
Closing in favor of #306.

**Pull request closed without merging**
