### PR TITLE
Clippy fixes for: plugin_sm

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Proposed changes

This is part of #825 - my patches to fix the clippy warnings in the `plugin_sm` crate.

## Types of changes

- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by initard — APPROVED** [review]
LGTM

**Comment by matthiasbeyer** [comment]
Seems CI was not triggered. Rebased and pushed for triggering CI.

**Comment by PradeepKiruvale** [comment]
> Seems CI was not triggered. Rebased and pushed for triggering CI.

Maybe because of conflicts. If there are any conflicts then the CI will not get triggered.

**Comment by matthiasbeyer** [comment]
No there were no conflicts. Sometimes, github just misses to start the CI... it happens... not that much of an issue if one can re-trigger it :smile:

**Comment by matthiasbeyer** [comment]
Assuming that this is already approved (rebase was only to trigger CI), feel free to revert if not.

**Pull request merged**
