### PR TITLE
Update from 0.5.1 to 0.6.2 failed

### PR DESCRIPTION
**Pull request by PradeepKiruvale**
## Proposed changes

- [x] Add `preinst` script for `debian` packages to upgrade tedge
- [x] Update `tedge_upgrade` script.
- [ ] Document about `tedge_upgrade` script in 0.7 release note.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by initard — APPROVED** [review]
LGTM

**Review by rina23q — APPROVED** [review]
I thought the `preinst` script will be just one liner calling 
```
./upgrade_tedge_0.6.sh
```
But then there is a question where to deploy the shell script. So, I'd approve.

**Comment by PradeepKiruvale** [comment]
> I thought the `preinst` script will be just one liner calling
> 
> ```
> ./upgrade_tedge_0.6.sh
> ```
> 
> But then there is a question where to deploy the shell script. So, I'd approve.

> I thought the `preinst` script will be just one liner calling
> 
> ```
> ./upgrade_tedge_0.6.sh
> ```
> 
> But then there is a question where to deploy the shell script. So, I'd approve.

When the preinst script runs, there will not be anything installed. So, the script can not be launched from the inside. So, everything has to be duplicated into the preist script.

**Comment by PradeepKiruvale** [comment]
closed

**Pull request merged**
