### PR TITLE
Dependabot

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Proposed changes

Using `cargo-outdated` as a required check for pull requests is not that nice, because it forces PR authors to update dependencies in a PR that was issued for something else entirely (actually that was my motivation for this PR as my CI job failed in #1237 exactly for that reason).

Hence, we add a dependabot configuration for the repository and also remove the cargo-outdated job from the pull request check workflow.

Posting this as a draft because we might want to discuss this before it goes in (@didier-wenzek and I briefly discussed this somewhere else AFAIR, but maybe there are some more questions)! Feel free to ask :smile: !

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by didier-wenzek** [comment]
* Failed `cargo outdated` checks don't block merge - for the reason you highlighted: a failure can be unrelated to the PR. 
* It makes sense to run such checks on the main branch on a daily basis.
* However, what are the differences between `dependabot` and `cargo outdated`?

**Comment by rina23q** [comment]
Actually, `cargo outdated` check is not required. If it's marked red, you are still able to merge it.

I like the idea, moving the `cargo outdated` to dependabot. But I have one scenario, the `cargo outdate` is useful if staying in the PR checks. 

- When a developer introduce a new external crate and if it's outdated, we can find it immediately in the PR.

How can we address this case?

**Comment by didier-wenzek** [comment]
> > It makes sense to run such checks on the main branch on a daily basis.
> 
> You mean via a cron job? Yes, but what do you do when this cron job fails? That's why I suggested dependabot, because it directly opens a PR and we only have to see whether CI succeeds with that updated dependency and merge if it does. Way less effort for maintainers 🥳 🎉!

I meant `schedule:  interval: daily` makes more sense then schedule on commit.

**Comment by matthiasbeyer** [comment]
> I meant schedule: interval: daily makes more sense then schedule on commit.

Yes, that is a (github-actions driven) cron job. And what do we do if that fails?

**Comment by didier-wenzek** [comment]
> Yes, that is a (github-actions driven) cron job. And what do we do if that fails?

How to say it? I agree with what you propose with dependabot!

**Comment by rina23q** [comment]
@matthiasbeyer I agree to have the dependabot definitely, but without having the replacement of warning developers who adds new outdated crates, I can't approve this PR. I would propose either 

a. Revert the deletion of cargo outdated from the pr-check workflow. Then, merge only the depandabot part by this PR. Later we will have a new PR to add your proposal, posting a warning comment on a PR when developer adds a new outdated crate. The PR should be together with the removal of cargo outdated from the pr-check workflow.

or

b. Add the mechanism to post a warning comment on the PR as you proposed in this PR.

**Comment by matthiasbeyer** [comment]
Please have a look whether this would suffice! :smile:

**Comment by matthiasbeyer** [comment]
So after investigating on #1219 I realized:

_Every_ PR will get a posting about out-of-date dependencies, as long as we have any outdated dependencies in the repository (i.e. `rumqttc`). I am not sure whether this is what we want! A check for only newly added dependencies is not trivial, AFAICS.

Of course the actual issue is that we have outdated dependencies, and that should be resolved! But the idea of having a bot post to every PR that there are outdated dependencies, even though the PRs do not even touch dependencies, might confuse contributors and maintainers alike.

I am not 100% sure on the way forward here.
What I would do, though, is: Remove the cargo-outdated-pr-posting job again.

Rationale being that we get PRs from dependabot for each outdated dependency anyways! So there will be one PR for each outdated dependency as soon as a dependency gets outdated! If a PR author introduces new dependencies, it should be job of the author and the reviewer to make sure that the newly introduces dependencies are up to date (or reasonably up to date). If something slips by, dependabot will file a PR within one day to update the dependency anyways!

I am curious what you think. :thinking:

**Comment by rina23q** [comment]
@matthiasbeyer Thanks for the very quick reaction! However, using `secrets.GITHUB_TOKEN` is a problem as we use fork-based PRs. It's also documented in the GitHub Action which you used to post a comment :cry: https://github.com/mshick/add-pr-comment#proxy-for-fork-based-prs

**Comment by matthiasbeyer** [comment]
> However, using secrets.GITHUB_TOKEN is a problem as we use fork-based PRs. 

ARG. Yes I keep missing that. Sorry.

**Comment by rina23q** [comment]
> What I would do, though, is: Remove the cargo-outdated-pr-posting job again.

I thought posting a comment is a good way, but it seems more complex than I expected. To compare the pros and cons, I would also go to the way: remove the Remove the cargo-outdated-pr-posting job again.

**Comment by matthiasbeyer** [comment]
Squashed the fixup commit and reverted the patch (I prefer not to squash the patch-and-revert because the revert documents why we didn't do this).

**Review by rina23q — APPROVED** [review]
Thank you!

**Pull request merged**
