### PR TITLE
Bump version of 'x509_parser' which uses 'time' instead of 'chrono'

### PR DESCRIPTION
**Pull request by makr11st**
## Proposed changes

`x509_parser 0.13` uses `time > 0.3`.

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
#625

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by didier-wenzek — COMMENTED** [review]
I'm okay to bump this version.

Can this error be related?

```
   Compiling tedge v0.5.3 (/home/runner/work/thin-edge.io/thin-edge.io/crates/core/tedge)
error: Test function downloader_download_processing_error has a return-type but no exected clause in the test-case. This is currently unsupported. See test-case documentation for more details.
   --> crates/common/download/src/download.rs:402:10
    |
402 |     ) -> anyhow::Result<()> {
    |          ^^^^^^

error: could not compile `download` due to previous error
```

**Comment by makr11st** [comment]
> I'm okay to bump this version.
> 
> Can this error be related?
> 
> ```
>    Compiling tedge v0.5.3 (/home/runner/work/thin-edge.io/thin-edge.io/crates/core/tedge)
> error: Test function downloader_download_processing_error has a return-type but no exected clause in the test-case. This is currently unsupported. See test-case documentation for more details.
>    --> crates/common/download/src/download.rs:402:10
>     |
> 402 |     ) -> anyhow::Result<()> {
>     |          ^^^^^^
> 
> error: could not compile `download` due to previous error
> ```

This is a funny one, for some reason a change in `test-case` from 1.2.1 to 1.2.3 breaks the compilation due to a change they made. I revert it manually to 1.2.1.

**Comment by matthiasbeyer** [comment]
> This is a funny one, for some reason a change in test-case from 1.2.1 to 1.2.3 breaks the compilation due to a change they made. I revert it manually to 1.2.1.

If this is reproducible, a bug report should be opened on their side, IMO! :+1:

**Comment by makr11st** [comment]
> > This is a funny one, for some reason a change in test-case from 1.2.1 to 1.2.3 breaks the compilation due to a change they made. I revert it manually to 1.2.1.
> 
> If this is reproducible, a bug report should be opened on their side, IMO! 👍

It seems they actually fixed a [bug](https://docs.rs/test-case/1.2.3/test_case/index.html#porting-from-rust-tests-with-result-types) which we were unknowingly using in this test.
I suppose I created another PR with updates to `test-case 2.0`.

**Review by didier-wenzek — APPROVED** [review]
Approved

**Pull request merged**
