### PR TITLE
Outsource contributing from governance

### LINKED ISSUE #1378: Align the GOVERNANCE.md and CONTRIBUTING.md documents
The governance model has been approved with this follow-up task:

- move the repository rules from the governance.md to the contributing.md document.

_Originally posted by @TheNeikos in https://github.com/thin-edge/thin-edge.io/pull/1203#discussion_r955893433_

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Closes #1378 

---

Just so we are on the same page: I don't think it should be merged like this! I think only moving the contents is okay, but we should also consolidate the contents of the "Repository maintenance" section with the rest of the "CONTRIBUTING.md" file.

Please reply shortly if I should do this in this PR (I am happy to!) and I will add more patches!

### CODE REVIEW

**Comment by TheNeikos** [comment]
I am fine with just merging it like this in a first step, and then look at the individual pieces in there and see if they still apply in a second step.

**Review by TheNeikos — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
I am okay with this. We should then create a follow-up issue for #1378 I guess?

**Comment by TheNeikos** [comment]
Yes, since this merges them and does not change the meaning, I think it should be at least logically separate.

**Review by didier-wenzek — APPROVED** [review]
Approved.

I prefer to merge this PR as is since there are a lot of line splits: adding content updates on top of that would make changes difficult to follow.

I will not close https://github.com/thin-edge/thin-edge.io/issues/1378 though.

**Pull request merged**
