### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gligorisaev**
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [x] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by didier-wenzek — COMMENTED** [review]
About the process:

* All the commits must be signed using `git commit -s`.
* The type of change should be specified. Here documentation.
* The appropriate checklist boxes should be ticked. Here the first two about the contributing guide and the CLA.

To be fair, I take the opportunity that you, the QA lead, missed these points to raise the question: "Are all these checkboxes useful?". If we don't check that this is actually respected by all, there is no point to request them. Currently none of the non-developer contributors follow these rules.

**Comment by rina23q** [comment]
@gligorisaev 
> All the commits must be signed using git commit -s.
You need it. Better you have such setup in your tool that you use.

Also, we have several README.md in our repository. From the commit message, it's not so obvious. My suggestion is
```
Update README.md in RobotFramework directory
```

**Review by rina23q — CHANGES_REQUESTED** [review]
The commit message should be improved and signed.

**Comment by gligorisaev** [comment]
I had no intention to open this PR

**Pull request closed without merging**
