### PR TITLE
remove unnecessary build jobs from pull-request-checks workflow

### PR DESCRIPTION
**Pull request by reubenmiller**
Signed-off-by: Reuben Miller <reuben.d.miller@gmail.com>

## Proposed changes

Remove unnecessary build jobs from the `pull-request-checks` workflow. The PR checks already run `cargo test` which will build the binary anyway. Removing these tasks, also makes the pr check quicker.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by rina23q — APPROVED** [review]
I like to remove those jobs :+1:

**Review by didier-wenzek — APPROVED** [review]
Approved

**Comment by didier-wenzek** [comment]
It's weird. Why is GitAction expecting status of checks that are no more launched?

**Comment by reubenmiller** [comment]
> It's weird. Why is GitAction expecting status of checks that are no more launched?

I’ll look at the GitHub config. I probably just have to remove it from the repo settings as well

**Comment by reubenmiller** [comment]
> > It's weird. Why is GitAction expecting status of checks that are no more launched?
> 
> I’ll look at the GitHub config. I probably just have to remove it from the repo settings as well

I have updated the branch protection rule to remove those checks.

**Pull request merged**
