### PR TITLE
Reorganise folders for system testing

### PR DESCRIPTION
**Pull request by abelikt**
## Proposed changes

Reorganise folders for system testing in order to have always a folder with the test topic and then a test within.
Already a part of CIT-442.

Afterwards we have all the tests sorted into one of these subfolders:

- apt_plugin
- communication_c8y
- environments
- local_mqtt
- monitoring
- mqtt_port
- software-management-end-to-end
- specifics_c8y
- tedge_behaviour
- tedge_calls
- tedge_mappers

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
-

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by rina23q** [comment]
Overall it looks good. A couple of points:
- Only `software-management-end-to-end` is kebab-case. I think it should be renamed in snake_case.
- `tedge_calls` and `tedge_behaviour` are confusing. `tedge_behaviour` can be `tedge_connect`.

**Review by PradeepKiruvale — COMMENTED** [review]
tedge_calls/behaviors can be clubbed right?, may be under tedge directory we can have these two sub directories
Same as c8y related tests

**Comment by albinsuresh** [comment]
How about a slightly hierarchical approach based on features? Here's one sample structure:

* environments
* tedge   //For all tedge utility tests
   * config    //For all tests around `tedge config` command
   * connect    //For all tests around `tedge connect` command
     * c8y
     * azure
   * cert   //For all tests around `tedge connect` command
   * mqtt   //For all tests around `tedge connect` command
* software-management
  * agent
  * plugins
    * apt
    * docker
* monitoring
  * agent
* mappers
   * c8y
   * azure
   * collectd
* cloud        // For cloud specific tests
   * c8y
   * azure
* lifecycle    // For lifecycle tests like installation, port change etc
* misc    //Miscellaneous tests

**Comment by makr11st** [comment]
As #565 has been merged this one can be closed now.

**Comment by abelikt** [comment]
New one was already merged

**Pull request closed without merging**
