### PR TITLE
fix: disconnect cleanly from local MQTT broker in tedge connect

### PR DESCRIPTION
**Pull request by reubenmiller**
## Proposed changes

Send MQTT `DISCONNECT` on local MQTT connections (in normal operation) in the `tedge connect` and `tedge reconnect` commands.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue

* https://github.com/thin-edge/thin-edge.io/issues/3024

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by reubenmiller** [comment]
First commit is to add the system test which should fail, and the second commit will be to fix the bug.

**Review by gligorisaev — COMMENTED** [review]
The added test step is doing what is intended for

**Review by gligorisaev — COMMENTED** [review]
The added test was reviewed and it is passing

**Review by Bravo555 — APPROVED** [review]
Confirming that this patch fixes the problem. 
Simple and sufficient for now, but another example of `rumqttc` API being a bit too verbose for our use case here. For a more elegant fix in the future, we should either use our `mqtt-channel` or create a wrapper over `rumqttc::Client` that at minimum provides a disconnect on drop.

**Review by rina23q — APPROVED** [review]

**Pull request merged**
