### PR TITLE
Fix missing features

### LINKED ISSUE #1032: Selective compilation of tedge-mapper crate fails
**Describe the bug**

Running `cargo check` from the repo root directory runs fine. But, building the mapper project separately with `cargo check -p tedge_mapper` , fails as follows:

```
Compiling tedge_mapper v0.6.0 (/home/rina/thinedge/thin-edge/crates/core/tedge_mapper)
error: The default runtime flavor is `multi_thread`, but the `rt-multi-thread` feature is disabled.
  --> crates/core/tedge_mapper/src/main.rs:76:1
   |
76 | #[tokio::main]
   | ^^^^^^^^^^^^^^
   |
   = note: this error originates in the attribute macro `tokio::main` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `process` in `tokio`
   --> crates/core/tedge_mapper/src/c8y/converter.rs:590:33
    |
590 |     let child = tokio::process::Command::new(&command)
    |                                 ^^^^^^^ not found in `tokio::process`
    |
help: consider importing one of these items
    |
1   | use clap::Command;
    |
1   | use std::process::Command;
    |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `tedge_mapper` due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Closes #1032 

I just saw #1032 and thought I can fix this real quick. :laughing: 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
The second patch needs discussion, I guess. Not sure whether this is the way to go...

**Review by rina23q — APPROVED** [review]
Thanks!

**Comment by rina23q** [comment]
> The second patch needs discussion, I guess. Not sure whether this is the way to go...

Oh I missed this comment. Maybe add @makr11st to the reviewer to discuss?

**Review by makr11st — APPROVED** [review]

**Review by albinsuresh — APPROVED** [review]

**Comment by albinsuresh** [comment]
I'm just curious how the build from the repo root was working even without these dependencies. I only see the `log-request-plugin` that previously had an explicit dependency defined on `rt-multi-thread`. But that crate was not a dependency of this `tedge-mapper` crate. So, where else was it "inheriting" this dependency from?

> The second patch needs discussion, I guess. Not sure whether this is the way to go...

Why do you think it needs a discussion? Is there some overhead that you're expecting?

**Comment by matthiasbeyer** [comment]
I think it has to do with how cargo resolves dependencies. When building the whole worktree, it finds all dependencies and includes them. The `process` feature of tokio is included somewhere, so it is included when building this particular crate. When building only the crate, the feature is not included and the build thus fails.

> Why do you think it needs a discussion? Is there some overhead that you're expecting?

After giving it a second thought: No! :laughing: The default tokio runtime is multithreaded, but the feature was missing in the dependency specification. I guess the same as with the `process` feature applies: Somewhere, multithreaded runtime was enabled and so this was not a problem, but when building only the one crate, the feature was missing and thus the build failed.

So I think these changes are exactly what is necessary so everything works as expected. :laughing:

**Comment by albinsuresh** [comment]
@matthiasbeyer Thanks for that explanation. Feel free to squash and merge this PR.

**Pull request merged**
