### PR TITLE
restart tedge mapper before tedge agent (#683)

### PR DESCRIPTION
**Pull request by initard**
Signed-off-by: initard <solo@softwareag.com>

## Proposed changes

Ensuring that on restart the mapper is available when `tedge_agent` starts. 

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by rina23q — COMMENTED** [review]
In this PR, we want to guarantee the order, 1) tedge-mapper-sm-c8y 2) tedge-agent. 
However, it's contradicting to `tedge connect`. `tedge connect` starts 1) tedge-agent 2) tedge-mapper-sm-c8y.
https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge/src/cli/connect/command.rs#L490

For software management, we need to start agent first because sm-mapper publishes software-list request at the start-up.

I am afraid that this change will affect software-list report. Any opinions here?

**Comment by didier-wenzek** [comment]
> I am afraid that this change will affect software-list report. Any opinions here?

This has definitely to be tested.

> In this PR, we want to guarantee the order, 1) tedge-mapper-sm-c8y 2) tedge-agent. However, it's contradicting to `tedge connect`. `tedge connect` starts 1) tedge-agent 2) tedge-mapper-sm-c8y. https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge/src/cli/connect/command.rs#L490
> For software management, we need to start agent first because sm-mapper publishes software-list request at the start-up.

Neither the sm-c8y not the agent should expect the other to start before. Both should be able to process messages that have been sent while not running (persistent session-id and subscriptions with QoS>0, no clean-session).

That said:
* Unfortunately, the sm-c8y and the agent seem to miss some messages on start.
* The current PR can only be a workaround - and can be merged only if not introducing an other issue.
* One point is missing to guarantee that both sm-c8y and the agent receive all the messages at the _very first_ start. __Both subscriptions need to be created before any message is sent__.

**Review by rina23q — APPROVED** [review]
Ok it seems work somehow.

**Comment by initard** [comment]
It really does seem to be fine :thinking:

**Comment by makr11st** [comment]
Sorry, a little late to the discussion. 
I suppose this actually introduces the above mentioned issue, however, we may not see it because the device is already created 
 and we have run at least once the mapper by `tedge connect` which sends the list at least once. Both `Requires` and `After` affect the boot up sequence and should not block force manual start/stop commands.

**Pull request merged**
