### PR TITLE
Update rustc: 1.58.1 -> 1.63.0

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Proposed changes

In #1279 we had a brief discussion whether to update rustc in our CI or not.

IMO there's no reason why we shouldn't, so here goes a PR to update rustc in all workflows.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Heh, this obviously has to go in _after_ #1279 :laughing:

**Comment by matthiasbeyer** [comment]
I guess this one also depends on #1349

**Comment by matthiasbeyer** [comment]
So it seems that before 1.63.0 the fix from #1310 does not work, and after 1.63.0 the fix from #1310 is required.

So I picked the patch from #1310 to this PR and am going to close #1310 in favour of this PR.

**Review by didier-wenzek — APPROVED** [review]
Approved

**Pull request merged**
