### PR TITLE
Run all pull request checks on the changes of workflow files

### PR DESCRIPTION
**Pull request by rina23q**
## Proposed changes
It is inconvenient if someone wants to change the workflow files, but the jobs are skipped in the pull requests. For example, https://github.com/thin-edge/thin-edge.io/pull/1263 should run all pull request checks workflow inside the PR. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
#1233 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by matthiasbeyer — APPROVED** [review]
This is cool!

**Review by didier-wenzek — APPROVED** [review]
Approved

**Comment by matthiasbeyer** [comment]
> Oh, I committed :D Should I revert my change? By the way, Cargo.* would be a better to include also Cargo.tom

(from [https://github.com/thin-edge/thin-edge.io/pull/1267#issuecomment-1191344744])

Actually I don't mind which patch gets merged. I added a bit more documentation [in my commit message](https://github.com/thin-edge/thin-edge.io/pull/1273/commits/36c254487cfc10e65ea2aadd4111adb25538c75b) - so if you want to take that, that'd be cool!

I you want, you can try some git goodness to make it work:

On the branch of this PR:

```
# fetch my PR to your local repository
git fetch <the name of your github remote> pull/1273/head

# Edit _your_ last commit, re-using my commit message
git commit --amend --reuse-message=FETCH_HEAD

# use the editor to edit that message to your liking. For example, add your signed-off-by
# after you're satisfied:

# force-push your PR branch
git push <the name of your github remote> improve/1233/run-all-pr-checks-when-workflow-changes --force
```

:smile:

**Comment by rina23q** [comment]
> I you want, you can try some git goodness to make it work:

@matthiasbeyer I did it. Let's merge this PR then! Thanks!

**Review by matthiasbeyer — APPROVED** [review]

**Comment by matthiasbeyer** [comment]
Really cool! :tada:

**Comment by matthiasbeyer** [comment]
The [CI error](https://github.com/thin-edge/thin-edge.io/runs/7448102406?check_suite_focus=true#step:7:656) seems to be unrelated to the changes here... maybe we should open an issue for that and re-try CI here? Not sure how to proceed...

**Comment by rina23q** [comment]
> The [CI error](https://github.com/thin-edge/thin-edge.io/runs/7448102406?check_suite_focus=true#step:7:656) seems to be unrelated to the changes here... maybe we should open an issue for that and re-try CI here? Not sure how to proceed...

I started retry. We need to open a new issue for the test failure, for sure. But on the other hand, definitely the failure is not related to this PR change :sweat:

**Comment by rina23q** [comment]
I would merge this PR as the test now passed. So it is sporadic failure...

**Comment by matthiasbeyer** [comment]
Whoop whoop, looks good now!

**Comment by matthiasbeyer** [comment]
> So it is sporadic failure...

Definitively needs an issue then, I guess. Sporadic failures should never happen :laughing: 

But :tada: on getting this landed! I already triggered dependabot to rebase its PRs.

**Pull request merged**
