### PR TITLE
Restructure directories of the workspace

### PR DESCRIPTION
**Pull request by makr11st**
## Proposed changes

This is to propose simplification to directory structure of thin-edge.io repository.

```md
thin-edge.io/
├─ crates/
│  ├─ common/
│  │  ├─ [common_crates_go_here/]
│  │  ├─ batcher
│  │  ├─ certificate
│  │  ├─ clock
│  │  ├─ download
│  │  ├─ flockfile
│  │  ├─ json_writer
│  │  ├─ mqtt_client
│  │  ├─ tedge_config
│  │  ├─ tedge_users
│  │  ├─ tedge_utils
│  │  ├─ ...
│  ├─ core/
│  │  ├─ [core_crates_go_here/]
│  │  ├─ c8y_smartrest
│  │  ├─ c8y_translator
│  │  ├─ json_sm
│  │  ├─ plugin_sm
│  │  ├─ tedge
│  │  ├─ tedge_agent
│  │  ├─ tedge_mapper
│  │  ├─ thin_edge_json
│  │  ├─ ...
│  ├─ tests/
│  │  ├─ [tests_related_crates_and_tools]
│  │  ├─ mqtt_tests
│─ plugins/
│  ├─ [plugins_go_here/]
│  ├─ tedge_apt_plugin
│  ├─ tedge_docker_plugin
│  ├─ tedge_dummy_plugin
│  ├─ ...
├─ Cargo.lock
├─ Cargo.toml
├─ README.md
```

My thoughts initially were to have single directory with all the crates, but then I thought that as we have so many crates it may be difficult to find one, so initially let's see what people think about a small split in 2 categories.

In terms of what goes where my thought was that:
`core` would contain binaries plus fata exchange libraries ( json_sm, c8y_smartrest, etc)
`common` would be helper crates, traits etc, eg tedge_utils, tedge_download, flockfile etc

Edit: Updated layout in the description.

This is proposal and I think there is a lot of flexibility in this layout, we may think about renaming some crates or adding prepends to make it easier to distinguish

WIP This change may require some tests or workflows updates, TBD after structure finalized.

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by didier-wenzek** [comment]
Nice proposal!

* My first idea was to have a flat hierarchy. But it makes sense to put the plugins apart.
* What is the criteria to put a crate in core? Is this for the binary as `tedge` or the mappers?

**Comment by makr11st** [comment]
Great questions, I forgot to put initial split in the list. I'll update it later.

My thoughts initially also were to have single directory with all the crates, but then I thought that as we have so many crates it may be difficult to find, so initially let's see what people think about a small split in 2 categories.

In terms of what goes where my thought was that:
`core` would contain binaries plus fata exchange libraries ( json_sm, c8y_smartrest, etc)
`common` would be helper crates, traits etc, eg tedge_utils, tedge_download, flockfile etc

**Review by PradeepKiruvale — COMMENTED** [review]
Good proposal. I feel it's better to wrap/abstract all the source code under 'src'. Readme, examples, tests can be in the root directory level itself.

**Comment by rina23q** [comment]
I want to rename `c8y_translator_lib` to `c8y_translator`! It is standing out.

**Comment by makr11st** [comment]
> I want to rename `c8y_translator_lib` to `c8y_translator`! It is standing out.

I'm more than happy to rename.

**Comment by makr11st** [comment]
As there are no more comments or suggestions I propose to move it to merge candidate.

**Comment by makr11st** [comment]
Updated the proposal, I moved out plugins directory as it may contain non-rust components: 

```plain
thin-edge.io/
├─ crates/
│  ├─ common/
│  │  ├─ [common_crates_go_here/]
│  │  ├─ batcher
│  │  ├─ certificate
│  │  ├─ clock
│  │  ├─ download
│  │  ├─ flockfile
│  │  ├─ json_writer
│  │  ├─ mqtt_client
│  │  ├─ tedge_config
│  │  ├─ tedge_users
│  │  ├─ tedge_utils
│  │  ├─ ...
│  ├─ core/
│  │  ├─ [core_crates_go_here/]
│  │  ├─ c8y_smartrest
│  │  ├─ c8y_translator_lib
│  │  ├─ json_sm
│  │  ├─ plugin_sm
│  │  ├─ tedge
│  │  ├─ tedge_agent
│  │  ├─ tedge_mapper
│  │  ├─ thin_edge_json
│  │  ├─ ...
│─ plugins/
│  ├─ [plugins_go_here/]
│  ├─ tedge_apt_plugin
│  ├─ tedge_docker_plugin
│  ├─ tedge_dummy_plugin
│  ├─ ...
├─ Cargo.lock
├─ Cargo.toml
├─ README.md
```

If all are happy with this struct I'll update to the latest and make sure all tests and workflows work with new struct.

**Review by didier-wenzek — COMMENTED** [review]
I approve this new structure. I just wonder where to put the test helper crates as `mqtt_tests`?

Why not `common`, `core`, and `tests` ?

**Comment by makr11st** [comment]
I'm happy about adding `tests`, no problem.

Regards,

Lukasz Woznicki
+44 7448078979

**Review by didier-wenzek — COMMENTED** [review]
Will approve: one just need to coordinate the merge with the pending PRs.

**Review by didier-wenzek — APPROVED** [review]
Approved

**Pull request merged**
