### PR TITLE
adjust the expected return code when user is missing "Tenant manager" admin rights

### PR DESCRIPTION
**Pull request by reey**
## Proposed changes

Improve the instructions about connecting to Cumulocity IoT:

* Use `Forbidden` and `Unauthorized` when referring to 403 and 401 error messages
* Include detailed description about each of the above errors
* Include a section of "common errors"
* Add info that SSO users are not supported

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [X] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by reubenmiller** [comment]
Thanks, I was also in the middle of some other additional tips, so I will push a few commits of my own to this PR, e.g.
* notice that user/email is case sensitive
* add same tips to the additional cert upload page (same tips which are in the c8y getting started section)

**Comment by reubenmiller** [comment]
Thanks @reey for the PR. I just pushes a commit which expands on the common errors reasons and added a screenshot as well of the Cumulocity IoT Global Role which is required.

**Comment by reey** [comment]
@reubenmiller maybe also mention that SSO users are not supported?

**Comment by reubenmiller** [comment]
> @reubenmiller maybe also mention that SSO users are not supported?

Do you know how a user can check if they are an SSO user or not?

**Review by reubenmiller — APPROVED** [review]

**Pull request merged**
