### PR TITLE
Clippy: Remove let unit

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Proposed changes

It seems that clippy failures were merged at some point... I don't know.

This fixes a clippy lint over all crates in the repository, namingly the [let-unit-value](https://rust-lang.github.io/rust-clippy/master/#let_unit_value) lint.

Nothing more was done in this patchset.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by initard — COMMENTED** [review]
Why is our workflow is not catching these in the cargo clippy job?

**Comment by matthiasbeyer** [comment]
> Why is our workflow is not catching these in the cargo clippy job?

That is indeed a good question :laughing: 

As @didier-wenzek indicated, this might be a new check and maybe because we're running rust 1.56 in CI, which is kinda old (current is 1.62) the old clippy may not have the check yet.
If we update our CI to recent rust, we might experience some more failures even!

**Comment by matthiasbeyer** [comment]
Interesting! Maybe it got promoted recently! :smile:

**Comment by rina23q** [comment]
We can merge it, however, the current `cargo clippy` in our workflow doesn't detect the warning, that means, in the future, someone can add let unit.

Which one should we go? Update our Rust version to 1.62.0 or keep 1.58.0 add ` -W clippy::pedantic` option?

**Comment by matthiasbeyer** [comment]
IMO updating rust is the way to go, as `clippy::pedantic` is rather strict and also might have false positives. From its documentation:

> lints which are rather strict or might have false positives

**Comment by initard** [comment]
@rina23q, @matthiasbeyer does it make sense to build for 1.58.1 (our MSRV) but check linting for 1.62.0?

**Comment by matthiasbeyer** [comment]
Yes I think that sounds like a good idea, IMO.

**Comment by matthiasbeyer** [comment]
After thinking again, I think that updating rust to 1.62.0 is the way to go. I mean for the whole project. Because there's no reason to keep it at an old version and having two different versions just introduces complexity in maintaining the CI ecosystem.

I'll file a PR to update it.

**Comment by matthiasbeyer** [comment]
:thinking: Are we gonna go forward with this?

**Comment by didier-wenzek** [comment]
> 🤔 Are we gonna go forward with this?

Yes, I will approve even if I'm okay with the `let () = ...` syntax. This will let us move freely with new version of clippy.

**Comment by matthiasbeyer** [comment]
Rebased and resolved merge conflicts.

**Review by didier-wenzek — APPROVED** [review]
Approved

**Pull request merged**
